### PR TITLE
Enable basic systems to work

### PR DESCRIPTION
**Pull request by ryo33**
## TODO
- [x] Signin system
- [x] Host page
- [x] Experiment page
- [x] Fetch initial data
- [x] Add React.js
- [x] Load experiments in ThemeServer

### CODE REVIEW

**Comment by ryo33** [comment]
Why does this branch have conflicts???????

**Comment by kagemiku** [comment]
I think that tab width is different between `master/.travis.yml` and `develop/.travis.yml`.

The tab width of `master/.travis.yml` is 2-spaces while `develop/.travis.yml`'s one is 4-spaces.

**Comment by kagemiku** [comment]
Please look at [master's blame](https://github.com/xeejp/xee/blame/master/.travis.yml) and [develop's blame](https://github.com/xeejp/xee/blame/develop/.travis.yml).

Some tabs in `master/.travis.yml` are vanished.....

**Comment by ryo33** [comment]
@kagemiku I see. Thank you.

**Comment by kagemiku** [comment]
🎉🎉

**Comment by ryo33** [comment]
We did it!!! :sunglasses:

**Pull request merged**
